#pragma once

#ifdef BE_PLATFORM_WINDOWS

extern BigLandsEngine::Application* BigLandsEngine::CreateApplication();

int main(int argc, char** argv)
{
	BigLandsEngine::Log::Init();
	BE_CORE_WARN("Initialized Log!");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	BE_ERROR("YOU ARE IN DEBUG MODE PLESE NOTE THAT THIS MODE MAY BE MORE DEFUCULT TO USE AND IS MADE TO DEBUG ERRORS IF YOU HAVE A ERROR IN YOUR GAME THIS IS GOOD FOR YOU");
	int a = 5;
	BE_INFO("Hello! Var={0}", a);

	auto app = BigLandsEngine::CreateApplication();
	app->Run();
	delete app;
}

#endif